services:
  account:
    image: "yewint04/account:neobank"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - neobank
  loan:
    image: "yewint04/loan:neobank"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - neobank
  cards:
    image: "yewint04/cards:neobank"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - neobank
networks:
  neobank:
    driver: "bridge"

