server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: "loans"
#  profiles:
#    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    hostname: "loans"
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    version: "1.0.0"
    description: "loans microservices for neobank"
