spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # this is important for gateway server
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s # this is for timeout configuration for all microservices ( accounts cards loans )
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Neobank Gateway server"
    version: "1.0.0"

logging:
  level:
    com:
      ye:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50  # if 50 percent of the request fails , it will go from the open state to the close state
      waitDurationInOpenState: 10000