services:
  configserver:
    image: "yewint04/configserver:neobank"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "yewint04/eurekaserver:neobank"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  account:
    image: "yewint04/account:neobank"
    container_name: account-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loan:
    image: "yewint04/loan:neobank"
    container_name: loan-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "yewint04/cards:neobank"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  neobank:
    driver: "bridge"

#   for mysql db
#services:
#  accountsdb:
#    image: mysql
#    container_name: accountsdb
#    ports:
#      - 3311:3306
#    environment:
#      MYSQL_DATABASE: accountsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  loansdb:
#    image: mysql
#    container_name: loansdb
#    ports:
#      - 3322:3306
#    environment:
#      MYSQL_DATABASE: loansdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  cardsdb:
#    image: mysql
#    container_name: cardsdb
#    ports:
#      - 3333:3306
#    environment:
#      MYSQL_DATABASE: cardsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  configserver:
#    image: "yewint04/configserver:neobank"
#    container_name: configserver-ms
#    ports:
#      - "8071:8071"
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    extends:
#      file: common-config.yml
#      service: microservice-base-config
#
#  account:
#    image: "yewint04/account:neobank"
#    container_name: account-ms
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
#    depends_on:
#      accountsdb:
#        condition: service_healthy
#      configserver:
#        condition: service_healthy
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  loan:
#    image: "yewint04/loan:neobank"
#    container_name: loan-ms
#    ports:
#      - "8090:8090"
#    environment:
#      SPRING_APPLICATION_NAME: "loans"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
#    depends_on:
#      loansdb:
#        condition: service_healthy
#      configserver:
#        condition: service_healthy
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  cards:
#    image: "yewint04/cards:neobank"
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    environment:
#      SPRING_APPLICATION_NAME: "cards"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
#    depends_on:
#      cardsdb:
#        condition: service_healthy
#      configserver:
#        condition: service_healthy
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#networks:
#  neobank:
#    driver: "bridge"
#
